#!/bin/sh

DIR="$(pwd)"

if [ -z "$1" ]; then
  target='.'
else
  target=$1
fi

hook_mode=0
if [ ! -z "$2" ] && [ "$2" == "hooks" ]; then
  hook_mode=1
fi

CYAN=$'\033[36m'
RED=$'\033[31m'
YELLOW=$'\033[33m'
MAGENTA=$'\033[35m'
NC=$'\033[0m'

ERROR_ESLINT=
AUTOFIXED_ESLINT=
exit_code=0

# --------------------------------------------------
# Affiche un message en rouge et stop le commit
# --------------------------------------------------
abort_message() {
    echo -e "\n${RED}/!\\ $1 /!\\${NC} \n"
    exit 1;
}

# --------------------------------------------------
# Verifie que eslint est install? dans le projet
# --------------------------------------------------
check_eslint() {
    if ! which eslint >/dev/null 2>&1
    then
        abort_message "esLint not installed, please install it and retry"
    fi
}

# --------------------------------------------------
# Lancement du controle de eslint sur un fichier
# --------------------------------------------------
control_eslint() {
    local eslint_result=
    local nb_error=0
    local target_file=

    eslint_result=$(eslint $DIR/$1 2>&1)

    nb_error=$(echo "$eslint_result" | grep -E "[0-9]+:[0-9]+\s*error\s*" | wc -l)
    if [ $nb_error -gt 0 ]
    then
        ERROR_ESLINT=$ERROR_ESLINT"\n    $nb_error in "$(echo "$1" | sed "s|^$target||g")
        exit_code=1
    fi

    if [ $hook_mode -eq 0 ] && [ $nb_error -gt 0 ]; then
        echo "$eslint_result"
    fi
}

# --------------------------------------------------
# Affiche les eslint error si il y en a
# --------------------------------------------------
print_hook_error() {
    if [[ "$ERROR_ESLINT" ]]
    then
        echo -e "\n${RED}ESLINT HOOKS ERROR found, commit aborted : ${NC}$ERROR_ESLINT"
        echo -e "${RED}    Commande : \n      make eslint TARGET_ESLINT=${CYAN}<FILE>${NC}"
    fi
}

check_eslint

for file in $(find $target -type f -name "*.js")
do
    control_eslint $file
done

if [ $hook_mode -eq 1 ]; then
  print_hook_error
  exit 0
fi

# if exit_code not 0, then exit with error
exit $exit_code
